#!/usr/bin/env python

Import("env")

common_nx = [
    "os_nx.cpp",
    "display_server_nx.cpp",
    "audio_driver_nx.cpp",
    "joypad_nx.cpp",
    "file_access_nx.cpp",
    "dir_access_nx.cpp",
    "netsocket_nx.cpp",
    "ip_nx.cpp",
]

if env["opengl3"]:
    common_nx.append("gl_manager_nx.cpp")

prog = env.add_program("#bin/godot", ["godot_nx.cpp"] + common_nx)
